export const PlatformRuntimeLayer = ({
  MarketDataSubscriptionProviderComponent,
  SharedMarketFlowRuntimeComponent,
  BroadFlowScannerRuntimeComponent,
  watchlistSymbols,
  broadFlowWatchlistSymbols = watchlistSymbols,
  activeWatchlistItems,
  quoteSymbols,
  sparklineSymbols,
  prioritySparklineSymbols = [],
  streamedQuoteSymbols,
  streamedAggregateSymbols,
  quoteStreamRuntimeEnabled,
  positionQuoteStreamRuntimeEnabled,
  quoteStreamDisabledReason,
  quoteStreamCoverageDiagnostics,
  marketStockAggregateStreamingEnabled,
  marketScreenActive,
  lowPriorityHistoryEnabled,
  sparklineHistoryEnabled,
  sparklineConcurrency,
  flowRuntimeEnabled,
  flowRuntimeIntervalMs,
  broadFlowRuntimeEnabled,
  broadFlowScannerConfig,
  broadFlowStartupDelayMs,
  platformFreshnessBus,
  children,
}) => (
  <MarketDataSubscriptionProviderComponent
    watchlistSymbols={watchlistSymbols}
    activeWatchlistItems={activeWatchlistItems}
    quoteSymbols={quoteSymbols}
    sparklineSymbols={sparklineSymbols}
    prioritySparklineSymbols={prioritySparklineSymbols}
    streamedQuoteSymbols={streamedQuoteSymbols}
    streamedAggregateSymbols={streamedAggregateSymbols}
    quoteStreamRuntimeEnabled={quoteStreamRuntimeEnabled}
    positionQuoteStreamRuntimeEnabled={positionQuoteStreamRuntimeEnabled}
    quoteStreamDisabledReason={quoteStreamDisabledReason}
    quoteStreamCoverageDiagnostics={quoteStreamCoverageDiagnostics}
    marketStockAggregateStreamingEnabled={marketStockAggregateStreamingEnabled}
    marketScreenActive={marketScreenActive}
    lowPriorityHistoryEnabled={lowPriorityHistoryEnabled}
    sparklineHistoryRuntimeEnabled={sparklineHistoryEnabled}
    sparklineConcurrency={sparklineConcurrency}
    platformFreshnessBus={platformFreshnessBus}
  >
    <SharedMarketFlowRuntimeComponent
      symbols={watchlistSymbols}
      enabled={flowRuntimeEnabled}
      intervalMs={flowRuntimeIntervalMs}
    />
    <BroadFlowScannerRuntimeComponent
      symbols={broadFlowWatchlistSymbols}
      enabled={broadFlowRuntimeEnabled}
      scannerConfig={broadFlowScannerConfig}
      startupDelayMs={broadFlowStartupDelayMs}
    />
    {children}
  </MarketDataSubscriptionProviderComponent>
);
