import React from "react";
import ResearchInsightsTabPanel from "./insights/ResearchInsightsTabPanel.jsx";

export default function ResearchWorkbenchInsights({
  bottomTab,
  onSelectTab,
  onRunOptimize,
  optRunning,
  optError,
  metrics,
  tradePnls,
  pnlDist,
  hourly,
  recoMatrix,
  recoComputing,
  recoError,
  onComputeReco,
  tfMin,
  strategy,
  onSelectStrategy,
  strategyPresets,
  strategyLabel,
  barsLength,
  dataSource,
  spotDataMeta,
  trades,
  skippedTrades,
  skippedByReason,
  replayRunStatus,
  replayRunError,
  backtestProgress,
  liveRunState,
  activeBacktestJob,
  activeOptimizerJob,
  displayedResultRecord,
  recentBacktestJobs,
  recentBacktestResults,
  recentOptimizerJobs,
  inputImpact,
  onRunInputImpact,
  rayalgoScoreStudy,
  onRunRayalgoScoringComparison,
  onRunRayalgoScoreStudy,
  onQueueRayalgoScoreStudy,
  onRefreshRayalgoScoreStudyCatalog,
  onSelectRayalgoScoreStudyPreset,
  onSelectRayalgoScoreStudyRun,
  onToggleRayalgoScoreStudyComparisonRun,
  onLoadRayalgoScoreStudyRunDetail,
  onImportRayalgoScoreStudyLocalArtifact,
  stagedConfigModel,
  runtimeData,
  logPage,
  setLogPage,
  selectedTradeId,
  onSelectTrade,
  optResults,
  onApplyOpt,
  onSaveOptBundle,
  onSaveHistoryBundle,
  onPromoteBundle,
  runHistory,
  optimizerHistory,
  rayalgoBundles,
  currentSetupSnapshot,
  currentBundleContext,
  onLoadHistoryRun,
  onOpenStoredResult,
  onApplyHistoryOptimizer,
  onClearRunHistory,
  onClearOptimizerHistory,
}) {
  return (
    <div style={{ display: "flex", flexDirection: "column", minHeight: 0 }}>
      <ResearchInsightsTabPanel
        bottomTab={bottomTab}
        onSelectTab={onSelectTab}
        onRunOptimize={onRunOptimize}
        optRunning={optRunning}
        optError={optError}
        metrics={metrics}
        tradePnls={tradePnls}
        pnlDist={pnlDist}
        hourly={hourly}
        recoMatrix={recoMatrix}
        recoComputing={recoComputing}
        recoError={recoError}
        onComputeReco={onComputeReco}
        tfMin={tfMin}
        strategy={strategy}
        onSelectStrategy={onSelectStrategy}
        strategyPresets={strategyPresets}
        strategyLabel={strategyLabel}
        barsLength={barsLength}
        dataSource={dataSource}
        spotDataMeta={spotDataMeta}
        trades={trades}
        skippedTrades={skippedTrades}
        skippedByReason={skippedByReason}
        replayRunStatus={replayRunStatus}
        replayRunError={replayRunError}
        backtestProgress={backtestProgress}
        liveRunState={liveRunState}
        activeBacktestJob={activeBacktestJob}
        activeOptimizerJob={activeOptimizerJob}
        displayedResultRecord={displayedResultRecord}
        recentBacktestJobs={recentBacktestJobs}
        recentBacktestResults={recentBacktestResults}
        recentOptimizerJobs={recentOptimizerJobs}
        inputImpact={inputImpact}
        onRunInputImpact={onRunInputImpact}
        rayalgoScoreStudy={rayalgoScoreStudy}
        onRunRayalgoScoringComparison={onRunRayalgoScoringComparison}
        onRunRayalgoScoreStudy={onRunRayalgoScoreStudy}
        onQueueRayalgoScoreStudy={onQueueRayalgoScoreStudy}
        onRefreshRayalgoScoreStudyCatalog={onRefreshRayalgoScoreStudyCatalog}
        onSelectRayalgoScoreStudyPreset={onSelectRayalgoScoreStudyPreset}
        onSelectRayalgoScoreStudyRun={onSelectRayalgoScoreStudyRun}
        onToggleRayalgoScoreStudyComparisonRun={onToggleRayalgoScoreStudyComparisonRun}
        onLoadRayalgoScoreStudyRunDetail={onLoadRayalgoScoreStudyRunDetail}
        onImportRayalgoScoreStudyLocalArtifact={onImportRayalgoScoreStudyLocalArtifact}
        stagedConfigModel={stagedConfigModel}
        runtimeData={runtimeData}
        logPage={logPage}
        setLogPage={setLogPage}
        selectedTradeId={selectedTradeId}
        onSelectTrade={onSelectTrade}
        optResults={optResults}
        onApplyOpt={onApplyOpt}
        onSaveOptBundle={onSaveOptBundle}
        onSaveHistoryBundle={onSaveHistoryBundle}
        onPromoteBundle={onPromoteBundle}
        runHistory={runHistory}
        optimizerHistory={optimizerHistory}
        rayalgoBundles={rayalgoBundles}
        currentSetupSnapshot={currentSetupSnapshot}
        currentBundleContext={currentBundleContext}
        onLoadHistoryRun={onLoadHistoryRun}
        onOpenStoredResult={onOpenStoredResult}
        onApplyHistoryOptimizer={onApplyHistoryOptimizer}
        onClearRunHistory={onClearRunHistory}
        onClearOptimizerHistory={onClearOptimizerHistory}
      />
    </div>
  );
}
