const SESSION_BLOCK_STAGE_DEFAULTS = Object.freeze({
  block_0: true,
  block_1: true,
  block_2: true,
  block_3: true,
  block_4: true,
  block_5: false,
  block_6: false,
  block_7: false,
  block_8: false,
  block_9: false,
  block_10: true,
  block_11: true,
  block_12: false,
});

const TRADE_DAY_STAGE_DEFAULTS = Object.freeze({
  trade_day_mon: true,
  trade_day_tue: true,
  trade_day_wed: true,
  trade_day_thu: true,
  trade_day_fri: true,
});

const REGIME_FILTER_SELECT_OPTIONS = Object.freeze([
  { value: "none", label: "All Regimes" },
  { value: "not_bear", label: "Skip Bear" },
]);

const STRIKE_SLOT_SELECT_OPTIONS = Object.freeze([
  { value: "auto", label: "ATM Auto" },
  { value: "0", label: "2 Below ATM" },
  { value: "1", label: "1 Below ATM" },
  { value: "2", label: "ATM Below" },
  { value: "3", label: "ATM Above" },
  { value: "4", label: "1 Above ATM" },
  { value: "5", label: "2 Above ATM" },
]);

export const BACKTEST_V2_STAGE_DEFAULTS = {
  runSettings: {
    profileName: "default",
    startDate: "",
    endDate: "",
    initialCapital: 25000,
  },
  exitGovernor: {
    trail_activation_atr_0dte: 0.4,
    trail_activation_atr_1dte: 0.6,
    trail_activation_atr_2to3dte: 0.85,
    trail_option_pnl_floor_0dte: 0.15,
    trail_option_pnl_floor_1dte: 0.1,
    trail_option_pnl_floor_2to3dte: 0.08,
    trail_entry_drawdown_pct: 0.18,
    trail_lock_ratio_initial: 0.4,
    trail_lock_ratio_max: 0.8,
    theta_tighten_0dte_30min: 0.1,
    theta_tighten_0dte_60min: 0.2,
    theta_tighten_0dte_90min: 0.3,
    theta_tighten_1to3_60min: 0.1,
    theta_tighten_1to3_120min: 0.15,
    tod_multiplier_open: 1.2,
    tod_multiplier_midmorning: 1.0,
    tod_multiplier_midday: 0.9,
    tod_multiplier_power_hour: 0.85,
    regime_multiplier_trending: 1.15,
    regime_multiplier_neutral: 1.0,
    regime_multiplier_choppy: 0.85,
    time_cliff_0dte_minutes: 45,
    time_cliff_1to3dte_eod: true,
    time_cliff_5plus_sessions: 2,
    time_cliff_profitable_override: true,
    max_loss_0dte_pct: 0.5,
    max_loss_1to3dte_pct: 0.4,
    max_loss_5plus_pct: 0.3,
    take_profit_pct: 0.35,
    zombie_bars: 30,
  },
  entryGate: {
    edge_ratio_skip: 1.1,
    edge_ratio_half: 1.3,
    edge_ratio_0dte_shift: 0.1,
    edge_ratio_weekend_shift: 0.15,
    vix_confluence_floor_low: 0.55,
    vix_confluence_floor_mid: 0.7,
    vix_confluence_floor_high: 0.85,
    vix_confluence_floor_very_high: 0.9,
    vix_25_30_trending_edge_shift: 0.1,
    vix_30_plus_trending_edge_shift: 0.2,
    vix_25_30_choppy_skip: true,
    vix_30_plus_choppy_skip: true,
    regime_expected_move_trending: 1.3,
    regime_expected_move_neutral: 1.0,
    regime_expected_move_choppy: 0.7,
    kelly_fraction: 0.25,
    kelly_floor_pct: 1.0,
    kelly_ceiling_pct: 3.0,
    kelly_lookback_trades: 40,
    max_position_pct: 5.0,
    max_exposure_pct: 15.0,
    mtf_confirm_upgrades_sizing: true,
    opposite_direction_skip: true,
    min_conviction: 0.48,
    rayalgo_min_quality_score: null,
    rayalgo_trend_change_min_quality_score: null,
    rayalgo_long_min_quality_score: null,
    rayalgo_short_min_quality_score: null,
    rayalgo_trend_change_long_min_quality_score: null,
    rayalgo_trend_change_short_min_quality_score: null,
    allow_shorts: false,
    regime_filter: "not_bear",
  },
  riskWarden: {
    daily_loss_limit_pct: 3.0,
    consecutive_loss_cooldown_count: 3,
    consecutive_loss_cooldown_minutes: 30,
    drawdown_throttle_pct: 5.0,
    drawdown_halt_pct: 10.0,
    max_concurrent_same_direction: 2,
    max_total_positions: 4,
    post_max_loss_cooldown_minutes: 10,
    persist_until_new_equity_high: true,
  },
  layers: {
    l1_fraction: 1.0,
    l2_fraction: 0.5,
    l3_fraction: 0.25,
    edge_bump_multiplier: 1.2,
    edge_skip_threshold: 1.1,
    max_layers_per_position: 3,
  },
  dteSelection: {
    base_dte_2m: 0,
    base_dte_5m_morning: 0,
    base_dte_5m_midday: 1,
    base_dte_5m_power_hour: 1,
    base_dte_15m: 2,
    dte_adj_trending: -1,
    dte_adj_neutral: 0,
    dte_adj_choppy: 1,
    dte_adj_high_vol: -1,
    dte_floor: 0,
    dte_cap: 5,
    midday_trending_0dte_confluence: 0.8,
    strike_slot: "auto",
  },
  executionPolicy: {
    regime_adapt: true,
    comm_per_contract: 0.65,
    slip_bps: 150,
  },
  sessionPolicy: {
    ...SESSION_BLOCK_STAGE_DEFAULTS,
    ...TRADE_DAY_STAGE_DEFAULTS,
  },
  rfCalibrator: {
    n_estimators: 200,
    max_depth: 8,
    min_samples_leaf: 10,
    min_trades_for_training: 200,
    retrain_interval: 75,
    rolling_window_size: 350,
    phase1_threshold: 200,
    phase2_threshold: 500,
  },
};

export function cloneBacktestV2StageDefaults() {
  return JSON.parse(JSON.stringify(BACKTEST_V2_STAGE_DEFAULTS));
}

export const BACKTEST_V2_RF_CALIBRATOR_SECTION = {
  key: "rfCalibrator",
  title: "RF Calibrator",
  subtitle: "Advanced model settings staged for later wiring.",
  fields: [
    { path: "rfCalibrator.n_estimators", label: "Estimators", step: 10, min: 1 },
    { path: "rfCalibrator.max_depth", label: "Max Depth", step: 1, min: 1 },
    { path: "rfCalibrator.min_samples_leaf", label: "Min Samples Leaf", step: 1, min: 1 },
    { path: "rfCalibrator.min_trades_for_training", label: "Min Trades Training", step: 10, min: 0 },
    { path: "rfCalibrator.retrain_interval", label: "Retrain Interval", step: 5, min: 1 },
    { path: "rfCalibrator.rolling_window_size", label: "Rolling Window", step: 10, min: 1 },
    { path: "rfCalibrator.phase1_threshold", label: "Phase 1 Threshold", step: 10, min: 0 },
    { path: "rfCalibrator.phase2_threshold", label: "Phase 2 Threshold", step: 10, min: 0 },
  ],
};

export const BACKTEST_V2_STAGE_SECTIONS = [
  {
    key: "runSettings",
    title: "Run Settings",
    subtitle: "Bucket-default run metadata for staging the new config surface.",
    fields: [
      { path: "runSettings.profileName", label: "Profile", type: "text", placeholder: "default", layout: "wide" },
      { path: "runSettings.startDate", label: "Start Date", type: "date", layout: "normal" },
      { path: "runSettings.endDate", label: "End Date", type: "date", layout: "normal" },
      { path: "runSettings.initialCapital", label: "Capital", type: "number", step: 1000, min: 1000, max: 100000000, layout: "normal" },
    ],
  },
  {
    key: "exitGovernor",
    title: "Exit Governor",
    subtitle: "Trail activation, time cliff, and max-loss controls from v2.",
    fields: [
      { path: "exitGovernor.trail_activation_atr_0dte", label: "Trail ATR 0DTE", step: 0.05 },
      { path: "exitGovernor.trail_activation_atr_1dte", label: "Trail ATR 1DTE", step: 0.05 },
      { path: "exitGovernor.trail_activation_atr_2to3dte", label: "Trail ATR 2-3DTE", step: 0.05 },
      { path: "exitGovernor.trail_option_pnl_floor_0dte", label: "Option Floor 0DTE", step: 0.01 },
      { path: "exitGovernor.trail_option_pnl_floor_1dte", label: "Option Floor 1DTE", step: 0.01 },
      { path: "exitGovernor.trail_option_pnl_floor_2to3dte", label: "Option Floor 2-3DTE", step: 0.01 },
      { path: "exitGovernor.trail_entry_drawdown_pct", label: "Trail Giveback", step: 0.01 },
      { path: "exitGovernor.trail_lock_ratio_initial", label: "Lock Ratio Initial", step: 0.05 },
      { path: "exitGovernor.trail_lock_ratio_max", label: "Lock Ratio Max", step: 0.05 },
      { path: "exitGovernor.theta_tighten_0dte_30min", label: "Theta Tighten 0DTE 30m", step: 0.05 },
      { path: "exitGovernor.theta_tighten_0dte_60min", label: "Theta Tighten 0DTE 60m", step: 0.05 },
      { path: "exitGovernor.theta_tighten_0dte_90min", label: "Theta Tighten 0DTE 90m", step: 0.05 },
      { path: "exitGovernor.theta_tighten_1to3_60min", label: "Theta Tighten 1-3DTE 60m", step: 0.05 },
      { path: "exitGovernor.theta_tighten_1to3_120min", label: "Theta Tighten 1-3DTE 120m", step: 0.05 },
      { path: "exitGovernor.tod_multiplier_open", label: "TOD Open", step: 0.05 },
      { path: "exitGovernor.tod_multiplier_midmorning", label: "TOD Midmorning", step: 0.05 },
      { path: "exitGovernor.tod_multiplier_midday", label: "TOD Midday", step: 0.05 },
      { path: "exitGovernor.tod_multiplier_power_hour", label: "TOD Power Hour", step: 0.05 },
      { path: "exitGovernor.regime_multiplier_trending", label: "Regime Trending", step: 0.05 },
      { path: "exitGovernor.regime_multiplier_neutral", label: "Regime Neutral", step: 0.05 },
      { path: "exitGovernor.regime_multiplier_choppy", label: "Regime Choppy", step: 0.05 },
      { path: "exitGovernor.time_cliff_0dte_minutes", label: "Time Cliff 0DTE", step: 5, min: 0 },
      { path: "exitGovernor.time_cliff_1to3dte_eod", label: "Time Cliff 1-3DTE EOD", type: "boolean" },
      { path: "exitGovernor.time_cliff_5plus_sessions", label: "Time Cliff 5+DTE Sessions", step: 1, min: 0, layout: "normal" },
      { path: "exitGovernor.time_cliff_profitable_override", label: "Profitable Override", type: "boolean" },
      { path: "exitGovernor.max_loss_0dte_pct", label: "Max Loss 0DTE", step: 0.05 },
      { path: "exitGovernor.max_loss_1to3dte_pct", label: "Max Loss 1-3DTE", step: 0.05 },
      { path: "exitGovernor.max_loss_5plus_pct", label: "Max Loss 5+DTE", step: 0.05 },
      { path: "exitGovernor.take_profit_pct", label: "Take Profit %", step: 0.05 },
      { path: "exitGovernor.zombie_bars", label: "Zombie Bars", step: 1, min: 1 },
    ],
  },
  {
    key: "entryGate",
    title: "Entry Gate",
    subtitle: "Edge thresholds, VIX gates, and Kelly sizing controls.",
    fields: [
      { path: "entryGate.edge_ratio_skip", label: "Edge Skip", step: 0.05 },
      { path: "entryGate.edge_ratio_half", label: "Edge Half", step: 0.05 },
      { path: "entryGate.edge_ratio_0dte_shift", label: "Edge 0DTE Shift", step: 0.05 },
      { path: "entryGate.edge_ratio_weekend_shift", label: "Edge Weekend Shift", step: 0.05 },
      { path: "entryGate.vix_confluence_floor_low", label: "VIX Floor Low", step: 0.05 },
      { path: "entryGate.vix_confluence_floor_mid", label: "VIX Floor Mid", step: 0.05 },
      { path: "entryGate.vix_confluence_floor_high", label: "VIX Floor High", step: 0.05 },
      { path: "entryGate.vix_confluence_floor_very_high", label: "VIX Floor Very High", step: 0.05 },
      { path: "entryGate.vix_25_30_trending_edge_shift", label: "VIX 25-30 Trending Shift", step: 0.05 },
      { path: "entryGate.vix_30_plus_trending_edge_shift", label: "VIX 30+ Trending Shift", step: 0.05 },
      { path: "entryGate.vix_25_30_choppy_skip", label: "VIX 25-30 Choppy Skip", type: "boolean" },
      { path: "entryGate.vix_30_plus_choppy_skip", label: "VIX 30+ Choppy Skip", type: "boolean" },
      { path: "entryGate.regime_expected_move_trending", label: "Expected Move Trending", step: 0.05 },
      { path: "entryGate.regime_expected_move_neutral", label: "Expected Move Neutral", step: 0.05 },
      { path: "entryGate.regime_expected_move_choppy", label: "Expected Move Choppy", step: 0.05 },
      { path: "entryGate.kelly_fraction", label: "Kelly Fraction", step: 0.05 },
      { path: "entryGate.kelly_floor_pct", label: "Kelly Floor %", step: 0.25 },
      { path: "entryGate.kelly_ceiling_pct", label: "Kelly Ceiling %", step: 0.25 },
      { path: "entryGate.kelly_lookback_trades", label: "Kelly Lookback", step: 5, min: 0 },
      { path: "entryGate.max_position_pct", label: "Max Position %", step: 0.5 },
      { path: "entryGate.max_exposure_pct", label: "Max Exposure %", step: 0.5 },
      { path: "entryGate.mtf_confirm_upgrades_sizing", label: "MTF Upgrades Sizing", type: "boolean" },
      { path: "entryGate.opposite_direction_skip", label: "Opposite Direction Skip", type: "boolean" },
      { path: "entryGate.min_conviction", label: "Min Conviction", step: 0.01 },
      { path: "entryGate.rayalgo_min_quality_score", label: "RayAlgo Quality Floor", step: 0.01, min: 0, max: 1 },
      { path: "entryGate.rayalgo_trend_change_min_quality_score", label: "Trend Change Floor", step: 0.01, min: 0, max: 1 },
      { path: "entryGate.rayalgo_long_min_quality_score", label: "Long Quality Floor", step: 0.01, min: 0, max: 1 },
      { path: "entryGate.rayalgo_short_min_quality_score", label: "Short Quality Floor", step: 0.01, min: 0, max: 1 },
      { path: "entryGate.rayalgo_trend_change_long_min_quality_score", label: "Trend Long Floor", step: 0.01, min: 0, max: 1 },
      { path: "entryGate.rayalgo_trend_change_short_min_quality_score", label: "Trend Short Floor", step: 0.01, min: 0, max: 1 },
      { path: "entryGate.allow_shorts", label: "Allow Shorts", type: "boolean" },
      { path: "entryGate.regime_filter", label: "Regime Filter", type: "select", options: REGIME_FILTER_SELECT_OPTIONS, layout: "normal" },
    ],
  },
  {
    key: "riskWarden",
    title: "Risk Warden",
    subtitle: "Account-level loss, throttle, and cooldown controls.",
    fields: [
      { path: "riskWarden.daily_loss_limit_pct", label: "Daily Loss Limit %", step: 0.25 },
      { path: "riskWarden.consecutive_loss_cooldown_count", label: "Consecutive Losses", step: 1, min: 0 },
      { path: "riskWarden.consecutive_loss_cooldown_minutes", label: "Cooldown Minutes", step: 5, min: 0 },
      { path: "riskWarden.drawdown_throttle_pct", label: "DD Throttle %", step: 0.5 },
      { path: "riskWarden.drawdown_halt_pct", label: "DD Halt %", step: 0.5 },
      { path: "riskWarden.max_concurrent_same_direction", label: "Max Same Direction", step: 1, min: 0 },
      { path: "riskWarden.max_total_positions", label: "Max Total Positions", step: 1, min: 1 },
      { path: "riskWarden.post_max_loss_cooldown_minutes", label: "Post Max-Loss Cooldown", step: 5, min: 0 },
      { path: "riskWarden.persist_until_new_equity_high", label: "Persist Until New High", type: "boolean" },
    ],
  },
  {
    key: "layers",
    title: "Layers",
    subtitle: "Stack fractions and layer gating controls.",
    fields: [
      { path: "layers.l1_fraction", label: "L1 Fraction", step: 0.05 },
      { path: "layers.l2_fraction", label: "L2 Fraction", step: 0.05 },
      { path: "layers.l3_fraction", label: "L3 Fraction", step: 0.05 },
      { path: "layers.edge_bump_multiplier", label: "Edge Bump", step: 0.05 },
      { path: "layers.edge_skip_threshold", label: "Edge Skip Threshold", step: 0.05 },
      { path: "layers.max_layers_per_position", label: "Max Layers", step: 1, min: 1 },
    ],
  },
  {
    key: "dteSelection",
    title: "DTE Selection",
    subtitle: "Timeframe and regime-based DTE selection from v2.",
    fields: [
      { path: "dteSelection.base_dte_2m", label: "Base DTE 2m", step: 1, min: 0 },
      { path: "dteSelection.base_dte_5m_morning", label: "Base DTE 5m Morning", step: 1, min: 0 },
      { path: "dteSelection.base_dte_5m_midday", label: "Base DTE 5m Midday", step: 1, min: 0 },
      { path: "dteSelection.base_dte_5m_power_hour", label: "Base DTE 5m Power Hour", step: 1, min: 0 },
      { path: "dteSelection.base_dte_15m", label: "Base DTE 15m", step: 1, min: 0 },
      { path: "dteSelection.dte_adj_trending", label: "DTE Adj Trending", step: 1 },
      { path: "dteSelection.dte_adj_neutral", label: "DTE Adj Neutral", step: 1 },
      { path: "dteSelection.dte_adj_choppy", label: "DTE Adj Choppy", step: 1 },
      { path: "dteSelection.dte_adj_high_vol", label: "DTE Adj High Vol", step: 1 },
      { path: "dteSelection.dte_floor", label: "DTE Floor", step: 1, min: 0 },
      { path: "dteSelection.dte_cap", label: "DTE Cap", step: 1, min: 0 },
      { path: "dteSelection.midday_trending_0dte_confluence", label: "Midday Trending 0DTE Confluence", step: 0.05, layout: "normal" },
      { path: "dteSelection.strike_slot", label: "Strike Slot", type: "select", options: STRIKE_SLOT_SELECT_OPTIONS, layout: "normal" },
    ],
  },
  {
    key: "executionPolicy",
    title: "Execution Policy",
    subtitle: "Friction and regime-adapt toggles applied at runtime.",
    fields: [
      { path: "executionPolicy.regime_adapt", label: "Regime Adapt", type: "boolean" },
      { path: "executionPolicy.comm_per_contract", label: "Commission / Contract", step: 0.05, min: 0 },
      { path: "executionPolicy.slip_bps", label: "Slippage Bps", step: 5, min: 0 },
    ],
  },
  {
    key: "sessionPolicy",
    title: "Session Policy",
    subtitle: "Trading day and intraday session access for staged runs.",
    fields: [
      { path: "sessionPolicy.trade_day_mon", label: "Mon", type: "boolean" },
      { path: "sessionPolicy.trade_day_tue", label: "Tue", type: "boolean" },
      { path: "sessionPolicy.trade_day_wed", label: "Wed", type: "boolean" },
      { path: "sessionPolicy.trade_day_thu", label: "Thu", type: "boolean" },
      { path: "sessionPolicy.trade_day_fri", label: "Fri", type: "boolean" },
      { path: "sessionPolicy.block_0", label: "09:30", type: "boolean" },
      { path: "sessionPolicy.block_1", label: "10:00", type: "boolean" },
      { path: "sessionPolicy.block_2", label: "10:30", type: "boolean" },
      { path: "sessionPolicy.block_3", label: "11:00", type: "boolean" },
      { path: "sessionPolicy.block_4", label: "11:30", type: "boolean" },
      { path: "sessionPolicy.block_5", label: "12:00", type: "boolean" },
      { path: "sessionPolicy.block_6", label: "12:30", type: "boolean" },
      { path: "sessionPolicy.block_7", label: "13:00", type: "boolean" },
      { path: "sessionPolicy.block_8", label: "13:30", type: "boolean" },
      { path: "sessionPolicy.block_9", label: "14:00", type: "boolean" },
      { path: "sessionPolicy.block_10", label: "14:30", type: "boolean" },
      { path: "sessionPolicy.block_11", label: "15:00", type: "boolean" },
      { path: "sessionPolicy.block_12", label: "15:30", type: "boolean" },
    ],
  },
];

function createFieldRegistry(sections = []) {
  return Object.freeze(
    sections.reduce((registry, section) => {
      section.fields.forEach((field) => {
        if (field?.path) {
          registry[field.path] = field;
        }
      });
      return registry;
    }, {}),
  );
}

export const BACKTEST_V2_STAGE_FIELDS_BY_PATH = createFieldRegistry(BACKTEST_V2_STAGE_SECTIONS);

function pickStageField(path) {
  const field = BACKTEST_V2_STAGE_FIELDS_BY_PATH[path];
  if (!field) {
    throw new Error(`Unknown backtest v2 staging field path: ${path}`);
  }
  return field;
}

function pickStageFields(paths = []) {
  return paths.map((path) => pickStageField(path));
}

function visualField(path, extra = {}) {
  return {
    field: pickStageField(path),
    ...extra,
  };
}

function compactSection(key, title, columns) {
  return {
    key,
    title,
    layout: "compact_row",
    columns,
  };
}

const DTE_TOD_SECTION = compactSection("tod", "TOD", 4);
const DTE_REGIME_SECTION = compactSection("regime", "Regime", 3);
const DTE_TIGHTENING_SECTION_3 = compactSection("tightening", "Tightening", 3);
const DTE_TIGHTENING_SECTION_2 = compactSection("tightening", "Tightening", 2);

export const BACKTEST_V2_STAGE_WORKFLOW_GROUPS = [
  {
    key: "setup",
    title: "Setup",
    subtitle: "Profile, dates, capital · v2 runSettings",
    fields: pickStageFields([
      "runSettings.profileName",
      "runSettings.startDate",
      "runSettings.endDate",
      "runSettings.initialCapital",
    ]),
  },
  {
    key: "entryFilters",
    title: "Entry Filters",
    subtitle: "Qualification gates, confluence, direction rules · v2 entryGate",
    fields: pickStageFields([
      "entryGate.edge_ratio_skip",
      "entryGate.edge_ratio_half",
      "entryGate.edge_ratio_0dte_shift",
      "entryGate.edge_ratio_weekend_shift",
      "entryGate.vix_confluence_floor_low",
      "entryGate.vix_confluence_floor_mid",
      "entryGate.vix_confluence_floor_high",
      "entryGate.vix_confluence_floor_very_high",
      "entryGate.vix_25_30_trending_edge_shift",
      "entryGate.vix_30_plus_trending_edge_shift",
      "entryGate.vix_25_30_choppy_skip",
      "entryGate.vix_30_plus_choppy_skip",
      "entryGate.regime_expected_move_trending",
      "entryGate.regime_expected_move_neutral",
      "entryGate.regime_expected_move_choppy",
      "entryGate.mtf_confirm_upgrades_sizing",
      "entryGate.opposite_direction_skip",
      "entryGate.min_conviction",
      "entryGate.rayalgo_min_quality_score",
      "entryGate.rayalgo_trend_change_min_quality_score",
      "entryGate.rayalgo_long_min_quality_score",
      "entryGate.rayalgo_short_min_quality_score",
      "entryGate.rayalgo_trend_change_long_min_quality_score",
      "entryGate.rayalgo_trend_change_short_min_quality_score",
      "entryGate.allow_shorts",
      "entryGate.regime_filter",
    ]),
  },
  {
    key: "exitLogic",
    title: "Exit Logic",
    subtitle: "Trail behavior, time cliffs, loss exits · v2 exitGovernor",
    fields: pickStageFields([
      "exitGovernor.trail_activation_atr_0dte",
      "exitGovernor.trail_activation_atr_1dte",
      "exitGovernor.trail_activation_atr_2to3dte",
      "exitGovernor.trail_option_pnl_floor_0dte",
      "exitGovernor.trail_option_pnl_floor_1dte",
      "exitGovernor.trail_option_pnl_floor_2to3dte",
      "exitGovernor.trail_entry_drawdown_pct",
      "exitGovernor.trail_lock_ratio_initial",
      "exitGovernor.trail_lock_ratio_max",
      "exitGovernor.theta_tighten_0dte_30min",
      "exitGovernor.theta_tighten_0dte_60min",
      "exitGovernor.theta_tighten_0dte_90min",
      "exitGovernor.theta_tighten_1to3_60min",
      "exitGovernor.theta_tighten_1to3_120min",
      "exitGovernor.tod_multiplier_open",
      "exitGovernor.tod_multiplier_midmorning",
      "exitGovernor.tod_multiplier_midday",
      "exitGovernor.tod_multiplier_power_hour",
      "exitGovernor.regime_multiplier_trending",
      "exitGovernor.regime_multiplier_neutral",
      "exitGovernor.regime_multiplier_choppy",
      "exitGovernor.time_cliff_0dte_minutes",
      "exitGovernor.time_cliff_1to3dte_eod",
      "exitGovernor.time_cliff_5plus_sessions",
      "exitGovernor.time_cliff_profitable_override",
      "exitGovernor.max_loss_0dte_pct",
      "exitGovernor.max_loss_1to3dte_pct",
      "exitGovernor.max_loss_5plus_pct",
      "exitGovernor.take_profit_pct",
      "exitGovernor.zombie_bars",
    ]),
  },
  {
    key: "sizingAndScaling",
    title: "Sizing & Scaling",
    subtitle: "Kelly, exposure, layering · v2 entryGate + layers",
    fields: pickStageFields([
      "entryGate.kelly_fraction",
      "entryGate.kelly_floor_pct",
      "entryGate.kelly_ceiling_pct",
      "entryGate.kelly_lookback_trades",
      "entryGate.max_position_pct",
      "entryGate.max_exposure_pct",
      "layers.l1_fraction",
      "layers.l2_fraction",
      "layers.l3_fraction",
      "layers.edge_bump_multiplier",
      "layers.edge_skip_threshold",
      "layers.max_layers_per_position",
    ]),
  },
  {
    key: "riskLimits",
    title: "Risk Limits",
    subtitle: "Account guardrails and cooldowns · v2 riskWarden",
    fields: pickStageFields([
      "riskWarden.daily_loss_limit_pct",
      "riskWarden.consecutive_loss_cooldown_count",
      "riskWarden.consecutive_loss_cooldown_minutes",
      "riskWarden.drawdown_throttle_pct",
      "riskWarden.drawdown_halt_pct",
      "riskWarden.max_concurrent_same_direction",
      "riskWarden.max_total_positions",
      "riskWarden.post_max_loss_cooldown_minutes",
      "riskWarden.persist_until_new_equity_high",
    ]),
  },
  {
    key: "dtePolicy",
    title: "DTE Policy",
    subtitle: "Contract duration selection · v2 dteSelection",
    fields: pickStageFields([
      "dteSelection.base_dte_2m",
      "dteSelection.base_dte_5m_morning",
      "dteSelection.base_dte_5m_midday",
      "dteSelection.base_dte_5m_power_hour",
      "dteSelection.base_dte_15m",
      "dteSelection.dte_adj_trending",
      "dteSelection.dte_adj_neutral",
      "dteSelection.dte_adj_choppy",
      "dteSelection.dte_adj_high_vol",
      "dteSelection.dte_floor",
      "dteSelection.dte_cap",
      "dteSelection.midday_trending_0dte_confluence",
      "dteSelection.strike_slot",
    ]),
  },
  {
    key: "executionPolicy",
    title: "Execution Policy",
    subtitle: "Signal eligibility, costs, and adapt toggles",
    fields: pickStageFields([
      "executionPolicy.regime_adapt",
      "executionPolicy.comm_per_contract",
      "executionPolicy.slip_bps",
    ]),
  },
  {
    key: "sessionPolicy",
    title: "Session Policy",
    subtitle: "Trading day and intraday access windows",
    fields: pickStageFields([
      "sessionPolicy.trade_day_mon",
      "sessionPolicy.trade_day_tue",
      "sessionPolicy.trade_day_wed",
      "sessionPolicy.trade_day_thu",
      "sessionPolicy.trade_day_fri",
      "sessionPolicy.block_0",
      "sessionPolicy.block_1",
      "sessionPolicy.block_2",
      "sessionPolicy.block_3",
      "sessionPolicy.block_4",
      "sessionPolicy.block_5",
      "sessionPolicy.block_6",
      "sessionPolicy.block_7",
      "sessionPolicy.block_8",
      "sessionPolicy.block_9",
      "sessionPolicy.block_10",
      "sessionPolicy.block_11",
      "sessionPolicy.block_12",
    ]),
  },
];

export const BACKTEST_V2_STAGE_VISUAL_GROUPS = [
  {
    key: "runSetup",
    title: "Run Setup",
    subtitle: "Profile, dates, and starting bankroll",
    tone: "setup",
    renderMode: "merged_sections",
    panels: [
      {
        key: "runContext",
        type: "fields",
        title: "Profile & Window",
        subtitle: "Choose the saved profile and test range",
        fields: [
          visualField("runSettings.profileName", { layout: "wide" }),
          visualField("runSettings.startDate", { layout: "normal" }),
          visualField("runSettings.endDate", { layout: "normal" }),
        ],
      },
      {
        key: "capitalBase",
        type: "fields",
        title: "Capital & Costs",
        subtitle: "Starting bankroll plus baseline trading friction",
        fields: [
          visualField("runSettings.initialCapital", {
            label: "Starting Capital",
            layout: "normal",
            range: { min: 1000, max: 100000000, step: 1000, format: "currency_compact" },
            showRangeTrack: false,
            showRangeCaption: false,
          }),
          visualField("executionPolicy.comm_per_contract", {
            label: "Commission / Contract",
            layout: "normal",
            range: { min: 0, max: 2, step: 0.05, format: "currency_compact" },
            showRangeTrack: false,
            showRangeCaption: false,
          }),
          visualField("executionPolicy.slip_bps", {
            label: "Slippage Bps",
            layout: "normal",
            range: { min: 0, max: 400, step: 5, format: "integer", discrete: true },
            showRangeTrack: false,
            showRangeCaption: false,
          }),
        ],
      },
      {
        key: "tradingCalendar",
        type: "fields",
        title: "Trading Calendar",
        subtitle: "Weekdays and session blocks allowed to open new trades",
        fields: [
          visualField("sessionPolicy.trade_day_mon"),
          visualField("sessionPolicy.trade_day_tue"),
          visualField("sessionPolicy.trade_day_wed"),
          visualField("sessionPolicy.trade_day_thu"),
          visualField("sessionPolicy.trade_day_fri"),
          visualField("sessionPolicy.block_0"),
          visualField("sessionPolicy.block_1"),
          visualField("sessionPolicy.block_2"),
          visualField("sessionPolicy.block_3"),
          visualField("sessionPolicy.block_4"),
          visualField("sessionPolicy.block_5"),
          visualField("sessionPolicy.block_6"),
          visualField("sessionPolicy.block_7"),
          visualField("sessionPolicy.block_8"),
          visualField("sessionPolicy.block_9"),
          visualField("sessionPolicy.block_10"),
          visualField("sessionPolicy.block_11"),
          visualField("sessionPolicy.block_12"),
        ],
      },
    ],
  },
  {
    key: "entryQualification",
    title: "Entry Qualification",
    subtitle: "Edge thresholds, calendar shifts, and confirmation gates",
    tone: "entry",
    renderMode: "merged_sections",
    panels: [
      {
        key: "edgeThresholds",
        type: "compare",
        title: "Edge Thresholds",
        subtitle: "Minimum edge needed to qualify or cut size",
        range: { min: 0.8, max: 1.6, step: 0.05, format: "ratio" },
        fields: [
          visualField("entryGate.edge_ratio_skip", { label: "Skip" }),
          visualField("entryGate.edge_ratio_half", { label: "Half Size" }),
        ],
      },
      {
        key: "calendarShift",
        type: "fields",
        title: "Calendar Shift",
        subtitle: "Weekend entry adjustment",
        fields: [
          visualField("entryGate.edge_ratio_weekend_shift", {
            label: "Weekend Shift",
            range: { min: 0, max: 0.3, step: 0.05, format: "ratio" },
          }),
        ],
      },
      {
        key: "confirmationRules",
        type: "fields",
        title: "Confirmation Rules",
        subtitle: "Directional and confirmation behavior",
        fields: [
          visualField("entryGate.mtf_confirm_upgrades_sizing", { label: "MTF Upgrades Sizing" }),
          visualField("entryGate.opposite_direction_skip", { label: "Opposite Direction Skip" }),
          visualField("entryGate.min_conviction", {
            label: "Min Conviction",
            range: { min: 0.3, max: 0.8, step: 0.01, format: "score" },
          }),
          visualField("entryGate.allow_shorts", { label: "Allow Shorts" }),
        ],
      },
      {
        key: "rayalgoQualification",
        type: "fields",
        title: "RayAlgo Qualification",
        subtitle: "Trend-change quality gates",
        fields: [
          visualField("entryGate.rayalgo_min_quality_score", {
            label: "Global Quality Floor",
            range: { min: 0.3, max: 0.8, step: 0.01, format: "score" },
          }),
          visualField("entryGate.rayalgo_trend_change_min_quality_score", {
            label: "Trend Change Floor",
            range: { min: 0.3, max: 0.8, step: 0.01, format: "score" },
          }),
          visualField("entryGate.rayalgo_long_min_quality_score", {
            label: "Long Floor",
            range: { min: 0.3, max: 0.8, step: 0.01, format: "score" },
          }),
          visualField("entryGate.rayalgo_short_min_quality_score", {
            label: "Short Floor",
            range: { min: 0.3, max: 0.8, step: 0.01, format: "score" },
          }),
          visualField("entryGate.rayalgo_trend_change_long_min_quality_score", {
            label: "Trend Long Floor",
            range: { min: 0.3, max: 0.8, step: 0.01, format: "score" },
          }),
          visualField("entryGate.rayalgo_trend_change_short_min_quality_score", {
            label: "Trend Short Floor",
            range: { min: 0.3, max: 0.8, step: 0.01, format: "score" },
          }),
        ],
      },
    ],
  },
  {
    key: "volatilityRegime",
    title: "Volatility & Regime",
    subtitle: "VIX floors, elevated-volatility shifts, and regime assumptions",
    tone: "entry",
    renderMode: "merged_sections",
    panels: [
      {
        key: "vixFloors",
        type: "rail_compare",
        title: "VIX Floors",
        subtitle: "Minimum confluence required by volatility bucket",
        showValueInLabels: true,
        hideFieldEditors: true,
        range: { min: 0.4, max: 1.0, step: 0.05, format: "score" },
        fields: [
          visualField("entryGate.vix_confluence_floor_low", { label: "Low" }),
          visualField("entryGate.vix_confluence_floor_mid", { label: "Mid" }),
          visualField("entryGate.vix_confluence_floor_high", { label: "High" }),
          visualField("entryGate.vix_confluence_floor_very_high", { label: "Very High" }),
        ],
      },
      {
        key: "highVolShifts",
        type: "compare",
        title: "High-Vol Shifts",
        subtitle: "Trending edge bumps when volatility is elevated",
        range: { min: 0, max: 0.3, step: 0.05, format: "ratio" },
        fields: [
          visualField("entryGate.vix_25_30_trending_edge_shift", { label: "VIX 25-30" }),
          visualField("entryGate.vix_30_plus_trending_edge_shift", { label: "VIX 30+" }),
        ],
      },
      {
        key: "highVolSkipRules",
        type: "fields",
        title: "Choppy Vetoes",
        subtitle: "Skip behavior when volatility is elevated and trend quality breaks down",
        fields: [
          visualField("entryGate.vix_25_30_choppy_skip"),
          visualField("entryGate.vix_30_plus_choppy_skip"),
        ],
      },
      {
        key: "expectedMove",
        type: "compare",
        title: "Expected Move Bias",
        subtitle: "Regime-weighted move assumptions",
        range: { min: 0.5, max: 1.5, step: 0.05, format: "ratio" },
        fields: [
          visualField("entryGate.regime_expected_move_trending", { label: "Trending" }),
          visualField("entryGate.regime_expected_move_neutral", { label: "Neutral" }),
          visualField("entryGate.regime_expected_move_choppy", { label: "Choppy" }),
        ],
      },
      {
        key: "regimePolicy",
        type: "fields",
        title: "Regime Policy",
        subtitle: "Filter and adapt behavior for regime-sensitive entries",
        fields: [
          visualField("entryGate.regime_filter", { layout: "normal" }),
          visualField("executionPolicy.regime_adapt"),
        ],
      },
    ],
  },
  {
    key: "sizingPlan",
    title: "Sizing Plan",
    subtitle: "Kelly bounds, exposure limits, and layer scaling",
    tone: "sizing",
    renderMode: "merged_sections",
    panels: [
      {
        key: "kellyControls",
        type: "fields",
        title: "Kelly Envelope",
        subtitle: "Sizing fraction, bounds, and training horizon",
        fields: [
          visualField("entryGate.kelly_fraction", { range: { min: 0, max: 1, step: 0.05, format: "percent_decimal" } }),
          visualField("entryGate.kelly_floor_pct", { range: { min: 0, max: 5, step: 0.25, format: "percent_points" } }),
          visualField("entryGate.kelly_ceiling_pct", { range: { min: 0, max: 5, step: 0.25, format: "percent_points" } }),
          visualField("entryGate.kelly_lookback_trades", { range: { min: 0, max: 100, step: 5, format: "trades", discrete: true } }),
        ],
      },
      {
        key: "exposureCaps",
        type: "compare",
        title: "Exposure Caps",
        subtitle: "Single-position versus total portfolio exposure",
        range: { min: 0, max: 25, step: 0.5, format: "percent_points" },
        fields: [
          visualField("entryGate.max_position_pct", { label: "Position" }),
          visualField("entryGate.max_exposure_pct", { label: "Total Exposure" }),
        ],
      },
      {
        key: "layerFractions",
        type: "compare",
        title: "Layer Fractions",
        subtitle: "Relative size of L1, L2, and L3 adds",
        range: { min: 0, max: 1, step: 0.05, format: "percent_decimal" },
        fields: [
          visualField("layers.l1_fraction", { label: "L1" }),
          visualField("layers.l2_fraction", { label: "L2" }),
          visualField("layers.l3_fraction", { label: "L3" }),
        ],
      },
      {
        key: "layerGates",
        type: "fields",
        title: "Layer Gates",
        subtitle: "How quickly layers expand or stop",
        fields: [
          visualField("layers.edge_bump_multiplier", { range: { min: 1, max: 2, step: 0.05, format: "ratio" } }),
          visualField("layers.edge_skip_threshold", { range: { min: 0.8, max: 1.4, step: 0.05, format: "ratio" } }),
          visualField("layers.max_layers_per_position", { range: { min: 1, max: 5, step: 1, format: "integer", discrete: true } }),
        ],
      },
    ],
  },
  {
    key: "exitLogic",
    title: "DTE Exit Profiles",
    subtitle: "Bucket-specific exits with shared trail controls",
    tone: "exit",
    layout: "pinned_row",
    panels: [
      {
        key: "zeroDteProfile",
        type: "fields",
        title: "0DTE",
        subtitle: "Same-day exits with trail, timing, and regime controls",
        fields: [
          visualField("exitGovernor.trail_activation_atr_0dte", {
            label: "Trail ATR",
            section: "Trail",
            range: { min: 0.2, max: 1.2, step: 0.05, format: "ratio" },
          }),
          visualField("exitGovernor.trail_option_pnl_floor_0dte", {
            label: "Profit Floor",
            section: "Profit Floor",
            range: { min: 0, max: 0.25, step: 0.01, format: "percent_decimal" },
          }),
          visualField("exitGovernor.trail_entry_drawdown_pct", {
            label: "Giveback",
            section: "Trail",
            range: { min: 0.02, max: 0.5, step: 0.01, format: "percent_decimal" },
          }),
          visualField("exitGovernor.theta_tighten_0dte_30min", {
            label: "30m",
            section: DTE_TIGHTENING_SECTION_3,
            range: { min: 0, max: 0.35, step: 0.05, format: "percent_decimal" },
          }),
          visualField("exitGovernor.theta_tighten_0dte_60min", {
            label: "60m",
            section: DTE_TIGHTENING_SECTION_3,
            range: { min: 0, max: 0.35, step: 0.05, format: "percent_decimal" },
          }),
          visualField("exitGovernor.theta_tighten_0dte_90min", {
            label: "90m",
            section: DTE_TIGHTENING_SECTION_3,
            range: { min: 0, max: 0.35, step: 0.05, format: "percent_decimal" },
          }),
          visualField("exitGovernor.time_cliff_0dte_minutes", {
            label: "Time Cliff",
            section: "Cliff",
            range: { min: 0, max: 120, step: 5, format: "minutes" },
            layout: "normal",
          }),
          visualField("exitGovernor.time_cliff_profitable_override", {
            label: "Profitable Override",
            section: "Cliff",
            layout: "normal",
          }),
          visualField("exitGovernor.max_loss_0dte_pct", {
            label: "Max Loss",
            section: "Loss",
            range: { min: 0.1, max: 0.6, step: 0.05, format: "percent_decimal" },
          }),
          visualField("exitGovernor.trail_lock_ratio_initial", {
            label: "Lock Initial",
            section: "Trail",
            range: { min: 0, max: 1, step: 0.05, format: "percent_decimal" },
          }),
          visualField("exitGovernor.trail_lock_ratio_max", {
            label: "Lock Max",
            section: "Trail",
            range: { min: 0, max: 1, step: 0.05, format: "percent_decimal" },
          }),
          visualField("exitGovernor.tod_multiplier_open", {
            label: "Open",
            section: DTE_TOD_SECTION,
            range: { min: 0.6, max: 1.3, step: 0.05, format: "ratio" },
          }),
          visualField("exitGovernor.tod_multiplier_midmorning", {
            label: "Mid-AM",
            section: DTE_TOD_SECTION,
            range: { min: 0.6, max: 1.3, step: 0.05, format: "ratio" },
          }),
          visualField("exitGovernor.tod_multiplier_midday", {
            label: "Midday",
            section: DTE_TOD_SECTION,
            range: { min: 0.6, max: 1.3, step: 0.05, format: "ratio" },
          }),
          visualField("exitGovernor.tod_multiplier_power_hour", {
            label: "Power",
            section: DTE_TOD_SECTION,
            range: { min: 0.6, max: 1.3, step: 0.05, format: "ratio" },
          }),
          visualField("exitGovernor.regime_multiplier_trending", {
            label: "Trend",
            section: DTE_REGIME_SECTION,
            range: { min: 0.6, max: 1.3, step: 0.05, format: "ratio" },
          }),
          visualField("exitGovernor.regime_multiplier_neutral", {
            label: "Neutral",
            section: DTE_REGIME_SECTION,
            range: { min: 0.6, max: 1.3, step: 0.05, format: "ratio" },
          }),
          visualField("exitGovernor.regime_multiplier_choppy", {
            label: "Choppy",
            section: DTE_REGIME_SECTION,
            range: { min: 0.6, max: 1.3, step: 0.05, format: "ratio" },
          }),
        ],
      },
      {
        key: "oneDteProfile",
        type: "fields",
        title: "1DTE",
        subtitle: "Next-session exits with shared trail, TOD, and regime controls",
        fields: [
          visualField("exitGovernor.trail_activation_atr_1dte", {
            label: "Trail ATR",
            section: "Trail",
            range: { min: 0.2, max: 1.2, step: 0.05, format: "ratio" },
          }),
          visualField("exitGovernor.trail_option_pnl_floor_1dte", {
            label: "Profit Floor",
            section: "Profit Floor",
            range: { min: 0, max: 0.25, step: 0.01, format: "percent_decimal" },
          }),
          visualField("exitGovernor.trail_entry_drawdown_pct", {
            label: "Giveback",
            section: "Trail",
            range: { min: 0.02, max: 0.5, step: 0.01, format: "percent_decimal" },
          }),
          visualField("exitGovernor.theta_tighten_1to3_60min", {
            label: "60m",
            section: DTE_TIGHTENING_SECTION_2,
            range: { min: 0, max: 0.35, step: 0.05, format: "percent_decimal" },
          }),
          visualField("exitGovernor.theta_tighten_1to3_120min", {
            label: "120m",
            section: DTE_TIGHTENING_SECTION_2,
            range: { min: 0, max: 0.35, step: 0.05, format: "percent_decimal" },
          }),
          visualField("exitGovernor.time_cliff_1to3dte_eod", {
            label: "End-of-Day Cliff",
            section: "Cliff",
            layout: "normal",
          }),
          visualField("exitGovernor.max_loss_1to3dte_pct", {
            label: "Max Loss",
            section: "Loss",
            range: { min: 0.1, max: 0.6, step: 0.05, format: "percent_decimal" },
          }),
          visualField("exitGovernor.trail_lock_ratio_initial", {
            label: "Lock Initial",
            section: "Trail",
            range: { min: 0, max: 1, step: 0.05, format: "percent_decimal" },
          }),
          visualField("exitGovernor.trail_lock_ratio_max", {
            label: "Lock Max",
            section: "Trail",
            range: { min: 0, max: 1, step: 0.05, format: "percent_decimal" },
          }),
          visualField("exitGovernor.tod_multiplier_open", {
            label: "Open",
            section: DTE_TOD_SECTION,
            range: { min: 0.6, max: 1.3, step: 0.05, format: "ratio" },
          }),
          visualField("exitGovernor.tod_multiplier_midmorning", {
            label: "Mid-AM",
            section: DTE_TOD_SECTION,
            range: { min: 0.6, max: 1.3, step: 0.05, format: "ratio" },
          }),
          visualField("exitGovernor.tod_multiplier_midday", {
            label: "Midday",
            section: DTE_TOD_SECTION,
            range: { min: 0.6, max: 1.3, step: 0.05, format: "ratio" },
          }),
          visualField("exitGovernor.tod_multiplier_power_hour", {
            label: "Power",
            section: DTE_TOD_SECTION,
            range: { min: 0.6, max: 1.3, step: 0.05, format: "ratio" },
          }),
          visualField("exitGovernor.regime_multiplier_trending", {
            label: "Trend",
            section: DTE_REGIME_SECTION,
            range: { min: 0.6, max: 1.3, step: 0.05, format: "ratio" },
          }),
          visualField("exitGovernor.regime_multiplier_neutral", {
            label: "Neutral",
            section: DTE_REGIME_SECTION,
            range: { min: 0.6, max: 1.3, step: 0.05, format: "ratio" },
          }),
          visualField("exitGovernor.regime_multiplier_choppy", {
            label: "Choppy",
            section: DTE_REGIME_SECTION,
            range: { min: 0.6, max: 1.3, step: 0.05, format: "ratio" },
          }),
        ],
      },
      {
        key: "twoToThreeDteProfile",
        type: "fields",
        title: "2-3DTE",
        subtitle: "Multi-session exits with shared trail, TOD, and regime controls",
        fields: [
          visualField("exitGovernor.trail_activation_atr_2to3dte", {
            label: "Trail ATR",
            section: "Trail",
            range: { min: 0.2, max: 1.2, step: 0.05, format: "ratio" },
          }),
          visualField("exitGovernor.trail_option_pnl_floor_2to3dte", {
            label: "Profit Floor",
            section: "Profit Floor",
            range: { min: 0, max: 0.25, step: 0.01, format: "percent_decimal" },
          }),
          visualField("exitGovernor.trail_entry_drawdown_pct", {
            label: "Giveback",
            section: "Trail",
            range: { min: 0.02, max: 0.5, step: 0.01, format: "percent_decimal" },
          }),
          visualField("exitGovernor.theta_tighten_1to3_60min", {
            label: "60m",
            section: DTE_TIGHTENING_SECTION_2,
            range: { min: 0, max: 0.35, step: 0.05, format: "percent_decimal" },
          }),
          visualField("exitGovernor.theta_tighten_1to3_120min", {
            label: "120m",
            section: DTE_TIGHTENING_SECTION_2,
            range: { min: 0, max: 0.35, step: 0.05, format: "percent_decimal" },
          }),
          visualField("exitGovernor.time_cliff_1to3dte_eod", {
            label: "End-of-Day Cliff",
            section: "Cliff",
            layout: "normal",
          }),
          visualField("exitGovernor.max_loss_1to3dte_pct", {
            label: "Max Loss",
            section: "Loss",
            range: { min: 0.1, max: 0.6, step: 0.05, format: "percent_decimal" },
          }),
          visualField("exitGovernor.trail_lock_ratio_initial", {
            label: "Lock Initial",
            section: "Trail",
            range: { min: 0, max: 1, step: 0.05, format: "percent_decimal" },
          }),
          visualField("exitGovernor.trail_lock_ratio_max", {
            label: "Lock Max",
            section: "Trail",
            range: { min: 0, max: 1, step: 0.05, format: "percent_decimal" },
          }),
          visualField("exitGovernor.tod_multiplier_open", {
            label: "Open",
            section: DTE_TOD_SECTION,
            range: { min: 0.6, max: 1.3, step: 0.05, format: "ratio" },
          }),
          visualField("exitGovernor.tod_multiplier_midmorning", {
            label: "Mid-AM",
            section: DTE_TOD_SECTION,
            range: { min: 0.6, max: 1.3, step: 0.05, format: "ratio" },
          }),
          visualField("exitGovernor.tod_multiplier_midday", {
            label: "Midday",
            section: DTE_TOD_SECTION,
            range: { min: 0.6, max: 1.3, step: 0.05, format: "ratio" },
          }),
          visualField("exitGovernor.tod_multiplier_power_hour", {
            label: "Power",
            section: DTE_TOD_SECTION,
            range: { min: 0.6, max: 1.3, step: 0.05, format: "ratio" },
          }),
          visualField("exitGovernor.regime_multiplier_trending", {
            label: "Trend",
            section: DTE_REGIME_SECTION,
            range: { min: 0.6, max: 1.3, step: 0.05, format: "ratio" },
          }),
          visualField("exitGovernor.regime_multiplier_neutral", {
            label: "Neutral",
            section: DTE_REGIME_SECTION,
            range: { min: 0.6, max: 1.3, step: 0.05, format: "ratio" },
          }),
          visualField("exitGovernor.regime_multiplier_choppy", {
            label: "Choppy",
            section: DTE_REGIME_SECTION,
            range: { min: 0.6, max: 1.3, step: 0.05, format: "ratio" },
          }),
        ],
      },
      {
        key: "fivePlusDteProfile",
        type: "fields",
        title: "5+DTE / Longer",
        subtitle: "Longer-dated exits with shared trail, TOD, and regime controls",
        fields: [
          visualField("exitGovernor.time_cliff_5plus_sessions", {
            label: "Time Cliff",
            section: "Cliff",
            range: { min: 0, max: 5, step: 1, format: "sessions", discrete: true },
            layout: "normal",
          }),
          visualField("exitGovernor.max_loss_5plus_pct", {
            label: "Max Loss",
            section: "Loss",
            range: { min: 0.1, max: 0.6, step: 0.05, format: "percent_decimal" },
          }),
          visualField("exitGovernor.trail_entry_drawdown_pct", {
            label: "Giveback",
            section: "Trail",
            range: { min: 0.02, max: 0.5, step: 0.01, format: "percent_decimal" },
          }),
          visualField("exitGovernor.trail_lock_ratio_initial", {
            label: "Lock Initial",
            section: "Trail",
            range: { min: 0, max: 1, step: 0.05, format: "percent_decimal" },
          }),
          visualField("exitGovernor.trail_lock_ratio_max", {
            label: "Lock Max",
            section: "Trail",
            range: { min: 0, max: 1, step: 0.05, format: "percent_decimal" },
          }),
          visualField("exitGovernor.tod_multiplier_open", {
            label: "Open",
            section: DTE_TOD_SECTION,
            range: { min: 0.6, max: 1.3, step: 0.05, format: "ratio" },
          }),
          visualField("exitGovernor.tod_multiplier_midmorning", {
            label: "Mid-AM",
            section: DTE_TOD_SECTION,
            range: { min: 0.6, max: 1.3, step: 0.05, format: "ratio" },
          }),
          visualField("exitGovernor.tod_multiplier_midday", {
            label: "Midday",
            section: DTE_TOD_SECTION,
            range: { min: 0.6, max: 1.3, step: 0.05, format: "ratio" },
          }),
          visualField("exitGovernor.tod_multiplier_power_hour", {
            label: "Power",
            section: DTE_TOD_SECTION,
            range: { min: 0.6, max: 1.3, step: 0.05, format: "ratio" },
          }),
          visualField("exitGovernor.regime_multiplier_trending", {
            label: "Trend",
            section: DTE_REGIME_SECTION,
            range: { min: 0.6, max: 1.3, step: 0.05, format: "ratio" },
          }),
          visualField("exitGovernor.regime_multiplier_neutral", {
            label: "Neutral",
            section: DTE_REGIME_SECTION,
            range: { min: 0.6, max: 1.3, step: 0.05, format: "ratio" },
          }),
          visualField("exitGovernor.regime_multiplier_choppy", {
            label: "Choppy",
            section: DTE_REGIME_SECTION,
            range: { min: 0.6, max: 1.3, step: 0.05, format: "ratio" },
          }),
        ],
      },
      {
        key: "sharedExitTargets",
        type: "fields",
        title: "Shared Exit Targets",
        subtitle: "Global fixed targets still used across all DTE buckets",
        fields: [
          visualField("exitGovernor.take_profit_pct", {
            label: "Take Profit",
            range: { min: 0.1, max: 2.5, step: 0.05, format: "percent_decimal" },
          }),
          visualField("exitGovernor.zombie_bars", {
            label: "Zombie Bars",
            range: { min: 1, max: 120, step: 1, format: "trades", discrete: true },
          }),
        ],
      },
    ],
  },
  {
    key: "accountGuardrails",
    title: "Account Guardrails",
    subtitle: "Loss envelopes, cooldowns, and directional caps",
    tone: "risk",
    renderMode: "merged_sections",
    panels: [
      {
        key: "lossEnvelope",
        type: "compare",
        title: "Loss Envelope",
        subtitle: "Daily loss and drawdown guardrails",
        range: { min: 0, max: 20, step: 0.5, format: "percent_points" },
        fields: [
          visualField("riskWarden.daily_loss_limit_pct", { label: "Daily Loss" }),
          visualField("riskWarden.drawdown_throttle_pct", { label: "DD Throttle" }),
          visualField("riskWarden.drawdown_halt_pct", { label: "DD Halt" }),
        ],
      },
      {
        key: "cooldownLogic",
        type: "fields",
        title: "Cooldown Logic",
        subtitle: "Loss streaks, post-loss pacing, and directional caps",
        fields: [
          visualField("riskWarden.consecutive_loss_cooldown_count", { range: { min: 0, max: 6, step: 1, format: "integer", discrete: true } }),
          visualField("riskWarden.consecutive_loss_cooldown_minutes", { range: { min: 0, max: 120, step: 5, format: "minutes" } }),
          visualField("riskWarden.post_max_loss_cooldown_minutes", { range: { min: 0, max: 60, step: 5, format: "minutes" } }),
          visualField("riskWarden.max_concurrent_same_direction", { range: { min: 0, max: 5, step: 1, format: "integer", discrete: true } }),
          visualField("riskWarden.max_total_positions", { range: { min: 1, max: 10, step: 1, format: "integer", discrete: true } }),
          visualField("riskWarden.persist_until_new_equity_high", { layout: "wide" }),
        ],
      },
    ],
  },
  {
    key: "dtePolicy",
    title: "DTE Selection",
    subtitle: "Contract duration rules and 0DTE overrides",
    tone: "dte",
    layout: "pinned_row",
    panels: [
      {
        key: "zeroDteEntryOverrides",
        type: "fields",
        title: "0DTE Entry Overrides",
        subtitle: "Extra edge and confluence requirements for same-day trades",
        fields: [
          visualField("entryGate.edge_ratio_0dte_shift", {
            label: "Edge Shift",
            range: { min: 0, max: 0.3, step: 0.05, format: "ratio" },
          }),
          visualField("dteSelection.midday_trending_0dte_confluence", {
            label: "Midday Confluence",
            range: { min: 0.5, max: 1.0, step: 0.05, format: "score" },
          }),
        ],
      },
      {
        key: "baseDte",
        type: "compare",
        title: "Base DTE by Timeframe",
        subtitle: "Default contract duration by session and chart rhythm",
        range: { min: 0, max: 5, step: 1, format: "integer", discrete: true },
        fields: [
          visualField("dteSelection.base_dte_2m", { label: "2m" }),
          visualField("dteSelection.base_dte_5m_morning", { label: "5m AM" }),
          visualField("dteSelection.base_dte_5m_midday", { label: "5m Mid" }),
          visualField("dteSelection.base_dte_5m_power_hour", { label: "5m Power" }),
          visualField("dteSelection.base_dte_15m", { label: "15m" }),
        ],
      },
      {
        key: "regimeDteAdjustments",
        type: "compare",
        title: "Regime Adjustments",
        subtitle: "How regime and volatility shift baseline DTE",
        range: { min: -2, max: 2, step: 1, format: "signed_integer", discrete: true },
        fields: [
          visualField("dteSelection.dte_adj_trending", { label: "Trending" }),
          visualField("dteSelection.dte_adj_neutral", { label: "Neutral" }),
          visualField("dteSelection.dte_adj_choppy", { label: "Choppy" }),
          visualField("dteSelection.dte_adj_high_vol", { label: "High Vol" }),
        ],
      },
      {
        key: "dteBounds",
        type: "compare",
        title: "Bounds",
        subtitle: "Hard floor and cap for final DTE selection",
        range: { min: 0, max: 7, step: 1, format: "integer", discrete: true },
        fields: [
          visualField("dteSelection.dte_floor", { label: "Floor" }),
          visualField("dteSelection.dte_cap", { label: "Cap" }),
        ],
      },
      {
        key: "strikeSelection",
        type: "fields",
        title: "Strike Selection",
        subtitle: "Default moneyness slot for option replay resolution",
        fields: [
          visualField("dteSelection.strike_slot", { layout: "normal" }),
        ],
      },
    ],
  },
];
