import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const sourcePath = resolve(
  import.meta.dirname,
  "../src/components/marketing/neural-core/pyrus-logo-points.ts",
);
const outputPath = resolve(
  import.meta.dirname,
  "../src/components/marketing/neural-core/pyrus-logo-points-compact.ts",
);
const source = readFileSync(sourcePath, "utf8");
const dataStart = source.indexOf("> = ") + 4;
const dataEnd = source.lastIndexOf(" as const;");

if (dataStart < 4 || dataEnd <= dataStart) {
  throw new Error("Unable to locate PYRUS_LOGO_PTS source data");
}

const points = JSON.parse(source.slice(dataStart, dataEnd));
const runtimePointCount = Math.min(28_000, points.length);
const pointsByAngle = [...points].sort(
  (left, right) =>
    Math.atan2(left[1], left[0]) - Math.atan2(right[1], right[0]),
);
const sampled = Array.from({ length: runtimePointCount }, (_, index) =>
  pointsByAngle[Math.floor((index * pointsByAngle.length) / runtimePointCount)],
);
const bytes = Buffer.allocUnsafe(runtimePointCount * 7);

for (let index = 0; index < sampled.length; index += 1) {
  const point = sampled[index];
  const offset = index * 7;
  bytes.writeInt16LE(Math.round(point[0] * 1_000), offset);
  bytes.writeInt16LE(Math.round(point[1] * 1_000), offset + 2);
  bytes[offset + 4] = Math.round(point[2] * 100);
  bytes[offset + 5] = Math.round(point[3] * 100);
  bytes[offset + 6] = Math.round(point[4] * 100);
}

const encoded = bytes.toString("base64");
const generated = `// Generated by scripts/generatePyrusLogoPointsCompact.mjs from the full
// 80,000-point source artwork. Coordinates retain the source's 0.001 precision;
// colors retain its 0.01 precision. Do not edit this file by hand.
const ENCODED_POINTS = "${encoded}";
const BYTES_PER_POINT = 7;

export type PyrusLogoPoint = readonly [number, number, number, number, number];

function decodePoints(): ReadonlyArray<PyrusLogoPoint> {
  const binary = atob(ENCODED_POINTS);
  const bytes = new Uint8Array(binary.length);
  for (let index = 0; index < binary.length; index += 1) {
    bytes[index] = binary.charCodeAt(index);
  }
  const view = new DataView(bytes.buffer);
  const points: PyrusLogoPoint[] = new Array(bytes.length / BYTES_PER_POINT);
  for (let index = 0; index < points.length; index += 1) {
    const offset = index * BYTES_PER_POINT;
    points[index] = [
      view.getInt16(offset, true) / 1_000,
      view.getInt16(offset + 2, true) / 1_000,
      bytes[offset + 4] / 100,
      bytes[offset + 5] / 100,
      bytes[offset + 6] / 100,
    ];
  }
  return points;
}

export const PYRUS_LOGO_PTS = decodePoints();
`;

if (process.argv.includes("--check")) {
  if (readFileSync(outputPath, "utf8") !== generated) {
    throw new Error(
      "Compact Pyrus logo points are stale; run pnpm run generate:logo-points",
    );
  }
} else {
  writeFileSync(outputPath, generated);
}
console.log(
  `${process.argv.includes("--check") ? "Verified" : "Generated"} ${runtimePointCount.toLocaleString()} compact points from ${points.length.toLocaleString()} source points`,
);
