import { mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { COMPANIES } from "../src/features/research/data/researchCompanies.js";
import { EDGES } from "../src/features/research/data/researchGraph.js";
import { THEMES, themeMatchesCompany } from "../src/features/research/data/researchThemes.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const outputDir = path.resolve(
  __dirname,
  "../src/features/research/data/theme-datasets",
);

function serialize(value) {
  return JSON.stringify(value);
}

async function main() {
  await rm(outputDir, { recursive: true, force: true });
  await mkdir(outputDir, { recursive: true });

  const themeIds = Object.keys(THEMES);

  await Promise.all(
    themeIds.map(async (themeId) => {
      const theme = THEMES[themeId];
      const companies = COMPANIES.filter((company) => themeMatchesCompany(theme, company));
      const tickers = new Set(companies.map((company) => company.t));
      const edges = EDGES.filter(([source, target]) => tickers.has(source) && tickers.has(target));

      const contents = `/* Auto-generated by scripts/generateResearchThemeDatasets.mjs */\nexport const THEME_ID = ${serialize(
        themeId,
      )};\nexport const COMPANIES = ${serialize(companies)};\nexport const EDGES = ${serialize(
        edges,
      )};\n\nexport default { THEME_ID, COMPANIES, EDGES };\n`;

      await writeFile(path.join(outputDir, `${themeId}.js`), contents, "utf8");
    }),
  );
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
